FROM python:2.7-alpine

LABEL maintainer="Robert Wojciechowski <robert@wojo.net>"

ENV PYTHONUNBUFFERED=1

RUN apk add --update --no-cache --virtual \
    curl \
    wget

RUN pip install --upgrade pip && \
    pip install --no-cache-dir influxdb

RUN adduser -D btmon
USER btmon

WORKDIR /opt/btmon
ADD . /opt/btmon

VOLUME /btmon.cfg

EXPOSE 5010

ENTRYPOINT ["./btmon.py"]
CMD ["-c", "/btmon.cfg"]