FROM alpine:3

LABEL maintainer="Robert Wojciechowski <robert@wojo.net>"

ENV PYTHONUNBUFFERED=1

RUN set -ex \
    && apk add --update --no-cache \
    curl \
    wget \
    python2

RUN python -m ensurepip

RUN set -ex && \
    pip install --upgrade --no-cache-dir pip && \
    pip install --no-cache-dir influxdb

WORKDIR /opt/btmon
ADD . /opt/btmon
RUN chmod 755 ./btmon.py

RUN adduser -D btmon
USER btmon

VOLUME /btmon.cfg

EXPOSE 5010

ENTRYPOINT ["./btmon.py"]
CMD ["-c", "/btmon.cfg"]
